"""empty message

Revision ID: e81f5f61b865
Revises: fbafa9db5ac2
Create Date: 2017-10-08 00:14:07.447626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e81f5f61b865'
down_revision = 'fbafa9db5ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('creation_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'creation_date')
    # ### end Alembic commands ###
