"""empty message

Revision ID: fad55da392bc
Revises: d05ecefea74b
Create Date: 2017-10-30 20:43:50.747544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fad55da392bc'
down_revision = 'd05ecefea74b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'data')
    # ### end Alembic commands ###
