"""empty message

Revision ID: fbafa9db5ac2
Revises: 1d7f3b76fe06
Create Date: 2017-10-05 00:59:19.842888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbafa9db5ac2'
down_revision = '1d7f3b76fe06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('upload_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'upload_date')
    # ### end Alembic commands ###
